interfaces:
  Groq llama-3.1-70b-versatile:
    api_key: null
    api_type: OpenAI
    max_tokens: 8000
    model: llama-3.2-90b-text-preview
    models_endpoint: /v1/chat/completions
    url: https://api.groq.com/openai/
  Ollama llama-3.2-3b:
    api_key: ''
    api_type: Ollama
    max_tokens: 8192
    model: llama3.2:3b
    models_endpoint: /api/tags
    url: http://192.168.76.130:11434
  Ollama llama3.1-8b:
    api_key: ''
    api_type: Ollama
    max_tokens: 8192
    model: llama3.1:8b
    models_endpoint: /api/tags
    url: http://192.168.76.130:11434
  OpenAI GPT gpt-4o-mini:
    api_key: null
    api_type: OpenAI
    max_tokens: 16384
    model: gpt-4o-mini
    models_endpoint: /v1/chat/completions
    url: https://api.openai.com/
seed_prompts: []
