auto_startup_workflows: []
interfaces:
  openai:
    api_key: ''
    api_url: https://api.openai.com
    max_tokens: null
    models_endpoint: /v1/chat/completions
    selected_model: gpt-4.1-nano
    type: OpenAI
seed_prompts: []
